[ { value: 'Pacific/Niue', label: '(GMT-11:00) Niue' },
  { value: 'Pacific/Pago_Pago', label: '(GMT-11:00) Pago Pago' },
  { value: 'Pacific/Honolulu', label: '(GMT-10:00) Hawaii Time' },
  { value: 'Pacific/Rarotonga', label: '(GMT-10:00) Rarotonga' },
  { value: 'Pacific/Tahiti', label: '(GMT-10:00) Tahiti' },
  { value: 'Pacific/Marquesas', label: '(GMT-09:30) Marquesas' },
  { value: 'America/Anchorage', label: '(GMT-09:00) Alaska Time' },
  { value: 'Pacific/Gambier', label: '(GMT-09:00) Gambier' },
  { value: 'America/Los_Angeles',
    label: '(GMT-08:00) Pacific Time' },
  { value: 'America/Tijuana',
    label: '(GMT-08:00) Pacific Time - Tijuana' },
  { value: 'America/Vancouver',
    label: '(GMT-08:00) Pacific Time - Vancouver' },
  { value: 'America/Whitehorse',
    label: '(GMT-08:00) Pacific Time - Whitehorse' },
  { value: 'Pacific/Pitcairn', label: '(GMT-08:00) Pitcairn' },
  { value: 'America/Dawson_Creek',
    label: '(GMT-07:00) Mountain Time - Dawson Creek' },
  { value: 'America/Denver', label: '(GMT-07:00) Mountain Time' },
  { value: 'America/Edmonton',
    label: '(GMT-07:00) Mountain Time - Edmonton' },
  { value: 'America/Hermosillo',
    label: '(GMT-07:00) Mountain Time - Hermosillo' },
  { value: 'America/Mazatlan',
    label: '(GMT-07:00) Mountain Time - Chihuahua, Mazatlan' },
  { value: 'America/Phoenix',
    label: '(GMT-07:00) Mountain Time - Arizona' },
  { value: 'America/Yellowknife',
    label: '(GMT-07:00) Mountain Time - Yellowknife' },
  { value: 'America/Belize', label: '(GMT-06:00) Belize' },
  { value: 'America/Chicago', label: '(GMT-06:00) Central Time' },
  { value: 'America/Costa_Rica', label: '(GMT-06:00) Costa Rica' },
  { value: 'America/El_Salvador',
    label: '(GMT-06:00) El Salvador' },
  { value: 'America/Guatemala', label: '(GMT-06:00) Guatemala' },
  { value: 'America/Managua', label: '(GMT-06:00) Managua' },
  { value: 'America/Mexico_City',
    label: '(GMT-06:00) Central Time - Mexico City' },
  { value: 'America/Regina',
    label: '(GMT-06:00) Central Time - Regina' },
  { value: 'America/Tegucigalpa',
    label: '(GMT-06:00) Central Time - Tegucigalpa' },
  { value: 'America/Winnipeg',
    label: '(GMT-06:00) Central Time - Winnipeg' },
  { value: 'Pacific/Galapagos', label: '(GMT-06:00) Galapagos' },
  { value: 'America/Bogota', label: '(GMT-05:00) Bogota' },
  { value: 'America/Cancun', label: '(GMT-05:00) America Cancun' },
  { value: 'America/Cayman', label: '(GMT-05:00) Cayman' },
  { value: 'America/Guayaquil', label: '(GMT-05:00) Guayaquil' },
  { value: 'America/Havana', label: '(GMT-05:00) Havana' },
  { value: 'America/Iqaluit',
    label: '(GMT-05:00) Eastern Time - Iqaluit' },
  { value: 'America/Jamaica', label: '(GMT-05:00) Jamaica' },
  { value: 'America/Lima', label: '(GMT-05:00) Lima' },
  { value: 'America/Nassau', label: '(GMT-05:00) Nassau' },
  { value: 'America/New_York', label: '(GMT-05:00) Eastern Time' },
  { value: 'America/Panama', label: '(GMT-05:00) Panama' },
  { value: 'America/Port-au-Prince',
    label: '(GMT-05:00) Port-au-Prince' },
  { value: 'America/Rio_Branco', label: '(GMT-05:00) Rio Branco' },
  { value: 'America/Toronto',
    label: '(GMT-05:00) Eastern Time - Toronto' },
  { value: 'Pacific/Easter', label: '(GMT-05:00) Easter Island' },
  { value: 'America/Caracas', label: '(GMT-04:30) Caracas' },
  { value: 'America/Asuncion', label: '(GMT-03:00) Asuncion' },
  { value: 'America/Barbados', label: '(GMT-04:00) Barbados' },
  { value: 'America/Boa_Vista', label: '(GMT-04:00) Boa Vista' },
  { value: 'America/Campo_Grande',
    label: '(GMT-03:00) Campo Grande' },
  { value: 'America/Cuiaba', label: '(GMT-03:00) Cuiaba' },
  { value: 'America/Curacao', label: '(GMT-04:00) Curacao' },
  { value: 'America/Grand_Turk', label: '(GMT-04:00) Grand Turk' },
  { value: 'America/Guyana', label: '(GMT-04:00) Guyana' },
  { value: 'America/Halifax',
    label: '(GMT-04:00) Atlantic Time - Halifax' },
  { value: 'America/La_Paz', label: '(GMT-04:00) La Paz' },
  { value: 'America/Manaus', label: '(GMT-04:00) Manaus' },
  { value: 'America/Martinique', label: '(GMT-04:00) Martinique' },
  { value: 'America/Port_of_Spain',
    label: '(GMT-04:00) Port of Spain' },
  { value: 'America/Porto_Velho',
    label: '(GMT-04:00) Porto Velho' },
  { value: 'America/Puerto_Rico',
    label: '(GMT-04:00) Puerto Rico' },
  { value: 'America/Santo_Domingo',
    label: '(GMT-04:00) Santo Domingo' },
  { value: 'America/Thule', label: '(GMT-04:00) Thule' },
  { value: 'Atlantic/Bermuda', label: '(GMT-04:00) Bermuda' },
  { value: 'America/St_Johns',
    label: '(GMT-03:30) Newfoundland Time - St. Johns' },
  { value: 'America/Araguaina', label: '(GMT-03:00) Araguaina' },
  { value: 'America/Argentina/Buenos_Aires',
    label: '(GMT-03:00) Buenos Aires' },
  { value: 'America/Bahia', label: '(GMT-03:00) Salvador' },
  { value: 'America/Belem', label: '(GMT-03:00) Belem' },
  { value: 'America/Cayenne', label: '(GMT-03:00) Cayenne' },
  { value: 'America/Fortaleza', label: '(GMT-03:00) Fortaleza' },
  { value: 'America/Godthab', label: '(GMT-03:00) Godthab' },
  { value: 'America/Maceio', label: '(GMT-03:00) Maceio' },
  { value: 'America/Miquelon', label: '(GMT-03:00) Miquelon' },
  { value: 'America/Montevideo', label: '(GMT-03:00) Montevideo' },
  { value: 'America/Paramaribo', label: '(GMT-03:00) Paramaribo' },
  { value: 'America/Recife', label: '(GMT-03:00) Recife' },
  { value: 'America/Santiago', label: '(GMT-03:00) Santiago' },
  { value: 'America/Sao_Paulo', label: '(GMT-02:00) Sao Paulo' },
  { value: 'Antarctica/Palmer', label: '(GMT-03:00) Palmer' },
  { value: 'Antarctica/Rothera', label: '(GMT-03:00) Rothera' },
  { value: 'Atlantic/Stanley', label: '(GMT-03:00) Stanley' },
  { value: 'America/Noronha', label: '(GMT-02:00) Noronha' },
  { value: 'Atlantic/South_Georgia',
    label: '(GMT-02:00) South Georgia' },
  { value: 'America/Scoresbysund',
    label: '(GMT-01:00) Scoresbysund' },
  { value: 'Atlantic/Azores', label: '(GMT-01:00) Azores' },
  { value: 'Atlantic/Cape_Verde',
    label: '(GMT-01:00) Cape Verde' },
  { value: 'Africa/Abidjan', label: '(GMT+00:00) Abidjan' },
  { value: 'Africa/Accra', label: '(GMT+00:00) Accra' },
  { value: 'Africa/Bissau', label: '(GMT+00:00) Bissau' },
  { value: 'Africa/Casablanca', label: '(GMT+00:00) Casablanca' },
  { value: 'Africa/El_Aaiun', label: '(GMT+00:00) El Aaiun' },
  { value: 'Africa/Monrovia', label: '(GMT+00:00) Monrovia' },
  { value: 'America/Danmarkshavn',
    label: '(GMT+00:00) Danmarkshavn' },
  { value: 'Atlantic/Canary',
    label: '(GMT+00:00) Canary Islands' },
  { value: 'Atlantic/Faroe', label: '(GMT+00:00) Faeroe' },
  { value: 'Atlantic/Reykjavik', label: '(GMT+00:00) Reykjavik' },
  { value: 'Etc/GMT',
    label: '(GMT+00:00) GMT (no daylight saving)' },
  { value: 'Europe/Dublin', label: '(GMT+00:00) Dublin' },
  ... 151 more items ]
