name: Cypress Tests
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Test newtelco/next-maintenance
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          browser: chrome
          record: true
          group: 'next-maintenance'
          build: npm run build
          start: npm run ci
          command: npm run cy:ci
          wait-on: 'http://localhost:4000'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CYPRESS_NEXTAUTH_URL: 'http://localhost:4000'
          NEXTAUTH_URL: 'http://localhost:4000'
          CYPRESS_BASE_URL: 'http://localhost:4000'
          CYPRESS_SITE_NAME: ${{ secrets.SITE_NAME }}
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
